### ISSUE TITLE
Slow linking speed

### ISSUE THREAD

**Issue by ZacWalk** [ZacWalk/mingw-woarm64-build#11]
Linker based on the prototype toolchain is slower than expected. Reported by Radek who has some statistics on it:

Package | Build | Target | System | CPU | RAM (GB) | binutils | make | Time
-- | -- | -- | -- | -- | -- | -- | -- | --
gcc | x86_64 | x86_64 | d16pls v5 | 16 | 32 | upstream | default | 3:56
gcc | x86_64 | x86_64 | Thinkpad | 8x2.6 GHz | 64 | upstream | default | 2:32
cross-gcc | x86_64 | x86_64 | Thinkpad | 8x2.6 GHz | 64 | ZacWalk (disable-threads) | default |  
gcc | x86_64@aarch64 | x86_64 | Volterra | 8x3.0 Ghz | 32 | upstream | default | 3:23
gcc | x86_64@aarch64 | x86_64 | Volterra | 8x3.0 Ghz | 32 | ZacWalk (enable-threads) | default | 6:24
gcc | x86_64 | x86_64 | DevBox | 16 | 64 | upstream | default | 2:20
gcc | x86_64 | x86_64 | DevBox | 16 | 64 | ZacWalk (disable-threads) | default |  
gcc | x86_64 | x86_64 | DevBox | 16 | 64 | ZacWalk (enable-threads) | default | 3:42

**Comment by ZacWalk** [comment]
A possible next step would be to test the x64 version of this toolchain with the aarch64 version. Maybe with OpenSSL as it takes a while to link.

**Comment by eukarpov** [comment]
Building binutils from upstream and aarch64-pe repos with the same configuration for x64 target  
Trying to reproduce linking issue by building gcc on WSL with different binutils

**Comment by eukarpov** [comment]
The same time for building with upstream, except for uploading artifacts

upstream 
https://github.com/eukarpov/mingw-woarm64-build/actions/runs/6849869106/job/18622914623
aarch64 branch
https://github.com/ZacWalk/mingw-woarm64-build/actions/runs/6808867666/job/18514057448

change
https://github.com/eukarpov/mingw-woarm64-build/compare/build-variants...eukarpov:mingw-woarm64-build:build_toolchain_upstream?expand=1

it looks like the regression is gone
