### ISSUE TITLE
Cannot unwind stack for x64 version of the toolchain

### ISSUE THREAD

**Issue by ZacWalk** [ZacWalk/mingw-woarm64-build#27]
If you build this toolchain for x64 the [test-pdata](https://github.com/ZacWalk/mingw-woarm64-build/blob/main/tests/test-pdata.c) test fails. Seems like the function entry cannot be found. This is a regression, probably in our SEH code. x64 and aarch64 use the same code to generate xdata or pdata sections with some if conditions. Something must be broken there for x64 as test-pdata does work for aarch64.

**Comment by movediedi** [comment]
Fix PR is here:  https://github.com/ZacWalk/binutils-woarm64/pull/1

**Comment by movediedi** [comment]
Closing this issue, as I believe the regression has been completely addressed.
